### ISSUE TITLE
Create an organization in Github for multiple repos

### ISSUE THREAD

**Issue by tgargula** [tgargula/beng-bot#29]
## Task
- [ ] Create an organization
- [ ] Add every team member
- [ ] Move Notion-Github integration and main repo to this organization
## Goal

We will probably have multiple repositories for different things. Even if we choose monorepo for frontend and backend, we will need some other repos for bots, other services etc.
